<?php

namespace AppBundle\Repository;

/**
 * campoAfinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoAfinRepository extends \Doctrine\ORM\EntityRepository
{
}
