<?php

namespace AppBundle\Repository;

/**
 * estadoSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class estadoSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
