<?php

namespace AppBundle\Repository;

/**
 * EstatuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstatuRepository extends \Doctrine\ORM\EntityRepository
{
}
