<?php

namespace AppBundle\Repository;

/**
 * solicitudnotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class solicitudnotaRepository extends \Doctrine\ORM\EntityRepository
{
}
