<?php

namespace AppBundle\Repository;

/**
 * usuarioCampoAfinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuarioCampoAfinRepository extends \Doctrine\ORM\EntityRepository
{
}
