# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db:
            entity:
                class: AppBundle:Usuario
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /login

            #
             #  access_control:
              #      - { path: ^/, roles: ROLE_ADMIN }
             #       - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            #        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            #        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY}

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~